### ISSUE TITLE
关于论文中loss在代码中的实现

### ISSUE THREAD

**Issue by evilvlso** [ShinkaiZ/CLCC-semi#1]
您好，请问论文中总的Loss包含三部分L_sup+L_contrast+L_consist,但在代码中只看到了L_sup+L_contrast，L_consist是不是在代码中没有实现呢？谢谢

**Comment by Shinkai2** [comment]
L_consist原本是在utils/run.py里面实现的，现在我把它一起放到losses.py里面了
